# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 11:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassessmentpermissions',
            name='instituion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.Institution'),
        ),
        migrations.AddField(
            model_name='userassessmentpermissions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.Assessment'),
        ),
        migrations.AddField(
            model_name='programme',
            name='programme_institution_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Boundary_Type'),
        ),
        migrations.AddField(
            model_name='assessment_studentgroup_association',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.Assessment'),
        ),
        migrations.AddField(
            model_name='assessment_studentgroup_association',
            name='student_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.StudentGroup'),
        ),
        migrations.AddField(
            model_name='assessment_lookup',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.Assessment'),
        ),
        migrations.AddField(
            model_name='assessment_institution_association',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.Assessment'),
        ),
        migrations.AddField(
            model_name='assessment_institution_association',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.Institution'),
        ),
        migrations.AddField(
            model_name='assessment_class_association',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.Assessment'),
        ),
        migrations.AddField(
            model_name='assessment_class_association',
            name='student_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.StudentGroup'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.Programme'),
        ),
        migrations.AddField(
            model_name='answer',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='answer',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='user2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userassessmentpermissions',
            unique_together=set([('user', 'instituion', 'assessment')]),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('assessment', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='assessment_studentgroup_association',
            unique_together=set([('assessment', 'student_group')]),
        ),
        migrations.AlterUniqueTogether(
            name='assessment_lookup',
            unique_together=set([('assessment', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='assessment_institution_association',
            unique_together=set([('assessment', 'institution')]),
        ),
        migrations.AlterUniqueTogether(
            name='assessment_class_association',
            unique_together=set([('assessment', 'student_group')]),
        ),
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together=set([('programme', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('question', 'object_id', 'flexi_data')]),
        ),
    ]
